
package cn.chd.webservice;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Method", targetNamespace = "http://webservice.chd.cn/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Method {


    /**
     * 
     */
    @WebMethod
    @Action(input = "http://webservice.chd.cn/Method/updateRequest", output = "http://webservice.chd.cn/Method/updateResponse")
    public void update();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://webservice.chd.cn/Method/insertRequest", output = "http://webservice.chd.cn/Method/insertResponse")
    public void insert();

}
