
package cn.chd.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MethodImplService", targetNamespace = "http://webservice.chd.cn/", wsdlLocation = "http://localhost:9093/WebServiceTest1?wsdl")
public class MethodImplService
    extends Service
{

    private final static URL METHODIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException METHODIMPLSERVICE_EXCEPTION;
    private final static QName METHODIMPLSERVICE_QNAME = new QName("http://webservice.chd.cn/", "MethodImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9093/WebServiceTest1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        METHODIMPLSERVICE_WSDL_LOCATION = url;
        METHODIMPLSERVICE_EXCEPTION = e;
    }

    public MethodImplService() {
        super(__getWsdlLocation(), METHODIMPLSERVICE_QNAME);
    }

    public MethodImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), METHODIMPLSERVICE_QNAME, features);
    }

    public MethodImplService(URL wsdlLocation) {
        super(wsdlLocation, METHODIMPLSERVICE_QNAME);
    }

    public MethodImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, METHODIMPLSERVICE_QNAME, features);
    }

    public MethodImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MethodImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Method
     */
    @WebEndpoint(name = "MethodImplPort")
    public Method getMethodImplPort() {
        return super.getPort(new QName("http://webservice.chd.cn/", "MethodImplPort"), Method.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Method
     */
    @WebEndpoint(name = "MethodImplPort")
    public Method getMethodImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.chd.cn/", "MethodImplPort"), Method.class, features);
    }

    private static URL __getWsdlLocation() {
        if (METHODIMPLSERVICE_EXCEPTION!= null) {
            throw METHODIMPLSERVICE_EXCEPTION;
        }
        return METHODIMPLSERVICE_WSDL_LOCATION;
    }

}
